### ISSUE TITLE
Show info dialog only once

### ISSUE THREAD

**Issue by tobiasKaminsky** [nicolasbrailo/PianOli#8] opened 2019-02-25 19:16 UTC
On my phone, when my baby is turning off screen and then on again, it shows the info dialog how to unlock every time.
Then my baby is a bit puzzled as she cannot directly play music.

So I suggest to show this dialog only once/ a few time / dismiss button.

If you agree/decide on one of these option, I can create a PR.

**Comment by nicolasbrailo** [comment] 2019-02-25 19:25
Hi @tobiasKaminsky. Thanks for the report!
A PR would be *AWESOME*! Thanks so much!

The lock request is done in Main_Activity::lock_app (which, in turn, just calls the underlying OS feature). The lock dialog itself is an Android feature, it's not created by the application (that is: the app says "hey Android, I want to be locked/pinned", Android says "OK, but let me ask the user first").

You're right that this dialog is show unnecessarily: it's displayed any time MainActivity is shown. It would be a good idea to figure out if the activity is already pinned, and only show this dialog if it is not. I'm not sure what would be the best way to detect this. Any ideas?

**Comment by tobiasKaminsky** [comment] 2019-02-26 06:29
> It would be a good idea to figure out if the activity is already pinned, and only show this dialog if it is not

This is a great idea, I'll have a look.

Additionally it would be nice to show the dialog only the first 5x, as for regular user it is also not needed to show the dialog on every fresh start.

**Comment by nicolasbrailo** [comment] 2019-02-26 08:54
> Additionally it would be nice to show the dialog only the first 5x [...]

As far as I know, that's not possible unless you run the application as root. It'd be quite bad if any arbitrary application could choose to pin itself to the screen and block the user from closing it. It's by design that Android will ask, each and every time, if the user allows the app to be pinned.

With that said: there's a "Draw over other apps" permission that may allow the "lock" functionality without going through a lock request. I didn't find a user friendly way of using this functionality, but it may be worth a try.

PS: I love NextCloud!

**Comment by nicolasbrailo** [comment] 2019-03-31 13:47
Latest commit should reduce number of app-pin requests as much as possible with the current solution. Please reopen if a better strategy is found.

**Closed by nicolasbrailo** 2019-03-31 13:47 UTC
